scm/urls.py
from django.conf.urls import patterns, include, url
# Uncomment the next two lines to enable the admin:
from django.contrib import admin


admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'scm.views.home'),
    url(r'^login/$', 'scm.views.user_login'),
    url(r'^logout/$', 'scm.views.user_logout'),
    # url(r'^scm/', include('scm.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url('', include('multas.urls')),
    url('', include('vehiculos.urls')),
    url('', include('pagos.urls')),
)

vehiculos/urls.py
# -*- coding: utf-8 *-*
from django.conf.urls import patterns, url


urlpatterns = patterns('vehiculos.views',
		url(r'^vehiculos/$', 'index'),
		url(r'^vehiculos/add/$', 'add_vehiculo'),
		url(r'^vehiculos/update/(?P<id>\d+)$', 'update_vehiculo'),
                #url(r'^lista/propietario', 'lista_propietario'),
                url(r'^vehiculos/ajax/add/propietario/', 'registrar_propietario'),
                url(r'^vehiculos/ajax/add/combustible/', 'registrar_combustible'),
                url(r'^vehiculos/ajax/add/sede/', 'registrar_sede'),
                url(r'^vehiculos/ajax/add/carroceria/', 'registrar_carroceria'),
                url(r'^vehiculos/ajax/add/color/', 'registrar_color'),
                url(r'^vehiculos/ajax/add/asociacion/', 'registrar_asociacion'),
                url(r'^vehiculos/ajax/add/marca/', 'registrar_marca'),
                url(r'^vehiculos/ajax/add/modelo/', 'registrar_modelo'),
                url(r'^vehiculos/ajax/add/clase/', 'registrar_clase'),
                url(r'^vehiculos/add/soat/$', 'add_soat'),
                url(r'^vehiculos/update/soat/(?P<id>\d+)$', 'update_soat'),
                url(r'^tarjeta-operatividad/add/$', 'registrar_tarjeta_operatividad'),
                url(r'^vehiculos/add/licencia/$', 'add_licencia'),
                url(r'^vehiculos/update/licencia/(?P<id>\d+)$', 'update_licencia'),
                url(r'^licencia/$', 'list_propietario_licencia'),
                url(r'^vehiculos/list/soat/$', 'list_soat'),
                url(r'^vehiculos/ajax/add/categoria/$', 'registar_categoria'),
                url(r'^tarjeta-operatividad/$', 'list_tarjeta_operatividad'),

	)

vehiculos/models.py
# -*- coding: utf-8 *-*
from django.db import models


class PropietarioConductor(models.Model):
    """Contiene los propietarios y conductores"""

    TIPO_PROPIETARIO = (
        ('P', 'PROPIETARIO'),
        ('C', 'CONDUCTOR'),
        ('T', 'CONDUCTOR / PROPIETARIO'),
        )

    TIPO_PERSONA = (
        ('N', 'NATURAL'), 
        ('J', 'JURIDICO'),
    )

    tipo_persona = models.CharField(max_length=1, choices=TIPO_PERSONA)
    nombre = models.CharField(max_length=255)
    direccion = models.CharField(max_length=150)
    telefono = models.CharField(max_length=10, null=True, blank=True)
    movil = models.CharField(max_length=12, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    tipo_propietario = models.CharField(max_length=1, choices=TIPO_PROPIETARIO)
    ruc = models.CharField(max_length=11, null=True, blank=True)
    dni = models.CharField(max_length=8, null=True, blank=True)

    def __unicode__(self):
        documento = ""
        if self.dni:
            documento = self.dni
        else:
            documento = self.ruc

        return "%s - %s" % (self.nombre.upper(), documento)


class LicenciaConducir(models.Model):
    """contiene la licecia (propietarios,conductores)"""
    nro_licencia = models.CharField(max_length=10)
    clase = models.CharField(max_length=3)
    categoria = models.CharField(max_length=3)
    fecha_emision = models.DateField(blank=True, null=True)
    fecha_vencimiento = models.DateField(blank=True, null=True)
    estado = models.BooleanField()
    propietarioconductor = models.ForeignKey(PropietarioConductor,
                                             blank=True, null=True)

    def __unicode__(self):

        return self.nro_licencia


class Categoria(models.Model):
    """"""
    descripcion = models.CharField(max_length=4, unique=True)

    def __unicode__(self):

        return self.descripcion


class Clase(models.Model):
    """Clase de vehiculos """
    descripcion = models.CharField(max_length=30, unique=True)    

    def __unicode__(self):

        return self.descripcion


class Asociacion(models.Model):
    """Asociacion de vehiculos"""
    nombre = models.CharField(max_length=50, unique=True)
    direccion = models.CharField(max_length=100)

    def __unicode__(self):

        return self.nombre


class Marca(models.Model):
    """Marca de vehiculos"""
    descripcion = models.CharField(max_length=50, unique=True)

    def __unicode__(self):

        return self.descripcion


class Color(models.Model):
    """Colores de vehiculos"""
    descripcion = models.CharField(max_length=50, unique=True)

    def __unicode__(self):

        return self.descripcion


class Modelo(models.Model):
    """Modelos de vehiculos"""
    descripcion = models.CharField(max_length=50, unique=True)

    def __unicode__(self):

        return self.descripcion


class Sede(models.Model):
    """Sede de reqgistros de tarjetas"""
    descripcion = models.CharField(max_length=50, unique=True)

    def __unicode__(self):

        return self.descripcion


class Carroceria(models.Model):
    nombre = models.CharField(max_length=30, unique=True)

    def __unicode__(self):
        return self.nombre


class Combustible(models.Model):
    nombre = models.CharField(max_length=30, unique=True)

    def __unicode__(self):
        return self.nombre


class Vehiculo(models.Model):
    """Contiene todos los vehiculos"""
    sede = models.ForeignKey(Sede, null=True, blank=True)
    placa_antigua  = models.CharField(max_length=15, null=True,blank=True)
    nro_placa = models.CharField(max_length=15, null=True, blank=True)
    nro_tarjeta = models.CharField(max_length=15, null=True, blank=True)
    year_fabricacion = models.IntegerField(null=True, blank=True)
    categoria = models.ForeignKey(Categoria, null=True, blank=True)
    clase = models.ForeignKey(Clase, null=True, blank=True)
    marca = models.ForeignKey(Marca, null=True, blank=True)
    modelo = models.ForeignKey(Modelo,null=True, blank=True)
    combustible = models.ForeignKey(Combustible, null=True, blank=True)
    carroceria = models.ForeignKey(Carroceria, null=True, blank=True)
    ejes = models.IntegerField(null=True, blank=True)
    color = models.ForeignKey(Color, null=True, blank=True)
    motor = models.CharField(max_length=30, null=True, blank=True)
    serie = models.CharField(max_length=50, unique=True)
    cilindros = models.IntegerField(null=True, blank=True)
    ruedas = models.IntegerField(null=True, blank=True)
    pasajeros = models.IntegerField(null=True, blank=True)
    asientos = models.IntegerField(null=True, blank=True)
    peso_neto = models.IntegerField(null=True, blank=True)
    peso_bruto = models.IntegerField(null=True, blank=True)
    longitud = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    altura = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    ancho = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    carga_util = models.IntegerField(null=True, blank=True)
    estado = models.BooleanField()


    def __unicode__(self):

        placa = ""
        if self.nro_placa:
            placa = self.nro_placa
        else:
            placa = "EN TRAMITE"

        return '(%s) %s' % (placa, self.serie)


class DetalleVehiculo(models.Model):
    """ Contiene la placa actual del vehiculo y su propietario"""
    propietario = models.ForeignKey(PropietarioConductor)
    vehiculo = models.ForeignKey(Vehiculo)
    asociacion = models.ForeignKey(Asociacion, blank=True, null=True)
    estado = models.BooleanField()

    def __unicode__(self):

        return '%s %s' % (self.vehiculo.__str__(), self.propietario.__str__())


class Soat(models.Model):
    """ Contiene soat de Vehiculo"""
    fecha_emision = models.DateField()
    fecha_caducidad = models.DateField()
    estado = models.BooleanField()
    #codigo_soat = models.CharField(max_length=8)
    vehiculo = models.ForeignKey(Vehiculo)

    def __unicode__(self):

        return str(self.estado)


class TarjetaOperatividad(models.Model):
    """Contiene Tarjeta Operatividad de Vehiculos"""

    fecha_expedicion = models.DateField()
    fecha_caducidad = models.DateField()
    estado = models.BooleanField()
    nro_regimen_individual = models.CharField(max_length=20)
    detalle_vehiculo = models.ForeignKey(DetalleVehiculo)
    recibo = models.IntegerField()

vehiculos/forms.py
# -*- coding: utf-8 *-*
from django import forms
from django.http import HttpResponse
from vehiculos.models import Sede, Modelo, Combustible, Clase, Marca
from vehiculos.models import Color, PropietarioConductor, Asociacion
from vehiculos.models import Vehiculo, Carroceria
#from django.forms import ModelForm 
from vehiculos.models import  Soat, DetalleVehiculo, Categoria
from vehiculos.models import LicenciaConducir
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.contrib import admin


class FormVehiculo(forms.Form):
    """Formulario generado a partir del modelo Usuario."""

    nro_tarjeta = forms.CharField(max_length=15, required=False)
    sede = forms.ModelChoiceField(queryset=Sede.objects.all(), required=False)
    nro_placa = forms.CharField(max_length=15, required=False)
    placa_antigua = forms.CharField(max_length=15, required=False)
    propietario = forms.ModelChoiceField(queryset=PropietarioConductor.objects.all())
    year_fabricacion = forms.IntegerField(label="Año de Fabricacion", 
                    widget=forms.TextInput(attrs={'maxlength': 4}), required=False)
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all(), required=False)
    marca = forms.ModelChoiceField(queryset=Marca.objects.all(), required=False)
    clase = forms.ModelChoiceField(queryset=Clase.objects.all(), required=False)
    modelo = forms.ModelChoiceField(queryset=Modelo.objects.all(), required=False)
    asociacion = forms.ModelChoiceField(queryset=Asociacion.objects.all(), required=False)
    combustible = forms.ModelChoiceField(Combustible.objects.all(), required=False)
    carroceria = forms.ModelChoiceField(queryset=Carroceria.objects.all(), required=False)
    ejes = forms.IntegerField(required=False)
    color = forms.ModelChoiceField(queryset=Color.objects.all(), required=False)
    motor = forms.CharField(max_length=30, required=False)
    cilindros = forms.IntegerField(required=False)
    serie = forms.CharField(max_length=50, help_text="Campo Obligatorio")
    ruedas = forms.IntegerField(required=False)
    pasajeros = forms.IntegerField(required=False)
    asientos = forms.IntegerField(required=False)
    peso_seco = forms.IntegerField(required=False)
    peso_bruto = forms.IntegerField(required=False)
    longitud = forms.DecimalField(max_digits=3, decimal_places=2, required=False)
    altura = forms.DecimalField(max_digits=3, decimal_places=2, required=False)
    ancho = forms.DecimalField(max_digits=3, decimal_places=2, required=False)
    carga_util = forms.IntegerField(required=False)
            
    
    def clean_motor(self):
        data = self.cleaned_data['motor']
        motor = Vehiculo.objects.filter(motor=data)
        if motor.exists():
            raise forms.ValidationError('Nro Motor ya Existe')
        return data

    def clean_nro_placa(self):
        data = self.cleaned_data['nro_placa']
        vehiculo = Vehiculo.objects.filter(nro_placa=data)
        if vehiculo.exists():
            raise forms.ValidationError('Placa Ya registrada')
        return data

    def clean_serie(self):
        data = self.cleaned_data['serie']
        serie = Vehiculo.objects.filter(serie=data)
        if serie.exists():
            raise forms.ValidationError('Serie Ya Existe')
        return data  
        
    def clean_nro_tarjeta(self):
        data = self.cleaned_data['nro_tarjeta']
        nro_tarjeta = Vehiculo.objects.filter(nro_tarjeta=data)
        if nro_tarjeta.exists():
            raise forms.ValidationError('Nro Tarjeta Ya Existe !Verifique')
        return data
 

class vehiculoAdmin(admin.ModelAdmin):
    search_fields = ('marca','modelo',)
    fieldsets = (
        (None, {
        'fields' : ('marca', 'serie',)}
        ),
        ( 'Descripcion', { 
        'fields':('nro_placa', ) }
        )

    )
   
    form = FormVehiculo


class FormSoat(forms.Form):
    fecha_emision = forms.DateField(label="Fecha Emision")
    fecha_caducidad = forms.DateField()
    codigo_soat = forms.CharField(max_length=8)
    vehiculo = forms.ModelChoiceField(queryset=Vehiculo.objects.all())


class FormTarjetaOperatividad(forms.Form):
    fecha_expedicion = forms.DateField(label="Fecha Emision")
    fecha_caducidad = forms.DateField(label="Fecha Caducidad")
    nro_regimen_individual = forms.CharField(max_length=20)
    detalle_vehiculo = forms.ModelChoiceField(label="Propietario", queryset=DetalleVehiculo.objects.filter(estado=True))
    recibo = forms.IntegerField()


class FormLicenciaConducir(forms.Form):
    """Registro de una licencia de conducir"""
    nro_licencia = forms.CharField(max_length=10)
    clase = forms.CharField(max_length=3, required=False)
    categoria = forms.CharField(max_length=3, required=False)
    fecha_emision = forms.DateField(required=False)
    fecha_vencimiento = forms.DateField(required=False)
    propietarioconductor = forms.ModelChoiceField(required=False, queryset=PropietarioConductor.objects.all())

scm/views.py
# -*- coding: utf-8 *-*
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def home(request):

	template_name = 'index.html'
	context = RequestContext(request)
	
	return render_to_response(template_name, context_instance=context)


def user_login(request):

	next = request.GET.get('next', '/')
	template_name = 'login.html'
	
	if request.method == 'POST':
		form = AuthenticationForm(request.POST)
		if form.is_valid:			
			usuario = request.POST['username']
			clave = request.POST['password']
			acceso = authenticate(username=usuario, password=clave)
			if acceso:
				if acceso.is_active:
					login(request, acceso)
					return HttpResponseRedirect(next)
				else:
					template_name = 'notactive.html'
			else:
				template_name = 'notuser.html'
	else:
		form = AuthenticationForm()

	context = RequestContext(request)
	data = {'form': form}

	return render_to_response(template_name, data, context)


@login_required(login_url='/login/')
def user_logout(request):
	
	logout(request)
	return HttpResponseRedirect('/')
	

scm/templates/vehiculos/add.html
{% extends 'base.html' %}
{% block title %}
	Nuevo Vehiculo
{% endblock %}
{% block css %}	
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/custom-theme/jquery-ui-1.8.20.custom.css"/>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/vehiculos/add.css"/>
{% endblock %}
{% block menu %}
<ul>
	<li><a class="list" href="/vehiculos/">Listado</a></li>

</ul>
{% endblock %}
{% block content %}
	<form class="well" id="frm_new_vehiculo" method="POST" action="">{% csrf_token %}
	
		<ul>
		{{ form.as_ul}}
		 
		</ul>
		<br/>
		<button class="save">Registar</button>
		<br/>
	</form>
	
		<form id="frm-propietario" class="modal fade hide"  method="POST">{% csrf_token %}
			<div class="modal-head">
				<a href="" class="close" data-dismiss="modal">x</a>
				<h3><i class="icon-hand-right"></i> Nuevo Propietario</h3>
			</div>
			<div class="modal-body">
				<ul>
				<li>
					<label for="id_tipo_persona">Tipo de Persona:</label>
					<select name="tipo_persona" id="id_tipo_persona">
						<option value="N">Natural</option>
						<option value="J">Juridico</option>
					</select>
				</li>
				<li>
					<label for="id_nombre">Nombre:</label>
                     <textarea id="id_nombre" name="nombre" cols="40" rows="2"></textarea>
				</li>
				<li>
					<label for="id_direccion">Direccion:</label>
					<textarea id="id_direccion" name="direccion" cols="40"rows="2"></textarea>
			    </li>
				<li>
					<label for="id_telefono">Telefono:</label><input type="text" id="id_telefono" maxlength="10" name="telefono" >
				</li>
				  <li>
				  	<label for="id_movil">Movil:</label><input type="text" id="id_movil" maxlength="12" name="movil">
				</li>
				<li>
					<label for="id_email">Email:</label><input type="text" id="id_email" name="email">
				</li>
				<li>
					<label for="id_ruc">Ruc:</label>
					<input type="text" id="id_ruc" maxlength="11" name="ruc">
				</li>
				<li>
					<label for="id_dni">Dni:</label>
					<input type="text" id="id_dni" maxlength="8" name="dni">
				</li>
				
			</ul>
			</div>
			<div class="modal-footer">
				<button type="button" id="btn-add-propietario" class="btn btn-success btn-large" >Registrar</button>
				<button class="btn" type="button" data-dismiss="modal">Cancelar</button>
			</div>
			
		</form>
	
	
		<form id="frm-combustible" method="POST" class="modal fade hide ">{% csrf_token %}
			<div class="modal-head">
				<a href="" class="close" data-dismiss="modal">x</a>
				<h3><i class="icon-hand-right"></i> Nuevo Combustible </h3>
			</div>
			<div class="modal-body">
				
			<ul>
			 	<li>
			 		<label for="id_combustible">Combustible</label><input type="text" id="id_combustible" name="nombre"></li>
			 </ul>
			</div>
			 <div class="modal-footer">
				<button type="button" id="btn-add-combustible" class="btn btn-success btn-large" >Registrar</button>
				<button class="btn" type="button" data-dismiss="modal">Cancelar</button>
			</div>
		</form>

	    <section id="ssede" class="modal fade hide ">
		<form id="frm-sede" method="POST" >{% csrf_token %} 
			<div class="modal-head">
				<a href="" class="close" data-dismiss="modal">x</a>
				<h3><i class="icon-hand-right"></i> Nueva Sede </h3>
			</div>
			<div class="modal-body">
			<ul>
			 	<li>
			 		<label for="id_sede">Sede</label><input type="text" id="id_sede" name="descripcion"></li>
			 </ul>
			 </div>
			 <div class="modal-footer">
				<button type="button" id="btn-add-sede" class="btn btn-success btn-large" >Registrar</button>
				<button class="btn" type="button" data-dismiss="modal">Cancelar</button>
			</div>
		</form>
     </section>
	<section id="scarroceria" style="display:none" class="modal fade hide ">
		<form id="frm-carroceria" method="POST" >{% csrf_token %}
			<div class="modal-hade">
			<a href="" class="close" data-dismiss="modal">x</a>
			<h3><i class="icon-hand-right"></i> Nueva Carroceria </h3>
			</div>
		<div class="modal-body">
			<ul>
			 	<li>
			 		<label for="id_nombre">Carroceria</label><input type="text" id="id_nombre" name="nombre">
			 	</li>
			 </ul>
		</div>				
		<div class="modal-footer">
			<button type="button" id="btn-add-carroceria"class="btn btn-success btn-large">Registra</button>
       		 <button type="button" class="btn" data-dismiss="modal"> Cancelar </button>
       	 </div>
		</form>
	</section>
	<section id="scolor" style="display:none;" class="modal  fade hide ">
		<form id="frm-color" method="POST">{% csrf_token %}
			<div class="moda-hade">
				<a href="" class="close" data-dismiss="modal">X</a>
				<h3><i class="icon-hand-right"></i>Nueva Color</h3>
			</div>
			<div class="modal-body">
				<ul>
			 	<li><label for="id_color">Color</label><input type="text" id="id_color" name="descripcion"></li>
			 </ul>
			</div>
			<div class="modal-footer">
				<button class="btn btn-success btn-large"type="button" id="btn-add-color">Registrar</button>
				<button class="btn" data-dismiss="modal">Cancelar</button>			
			</div>
		</form>
	</section>
	<section id="sasociacion" style="display:none;" class="modal fade hide">
		<form id="frm-asociacion" method="POST"> {% csrf_token %}
			<div class="modal-hade">
				<a href="" class="close" data-dismiss="modal" >x</a>
				<h3><i class="icon-hand-right"></i> Nueva Asociación</h3>
			</div>
			<div class="modal-body">
				
			<ul>
			 	<li>
			 		<label for="id_nombre">Nombre:</label><input type="text" id="id_nombre" name="nombre">
			 	</li>

			 	<li>
			 		<label for="id_direccion">Direccion:</label><input type="text" id="id_direccion" name="direccion">
			 	</li>
			
			 </ul>
			</div>
			<div class="modal-footer">
				<button type="button"class="btn btn-success btn-large" id="btn-add-asociacion">Registrar</button>
				<button class="btn" data-dismiss="modal">Cancelar</button>
			</div>
		</form>
	</section>
	<section id="smarca" style="display:none" class="modal fade hide">
		<form id="frm-marca" method="POST">{% csrf_token %}

			<div class="modal-hade">
				<a href="" class="close" data-dismiss="modal">x</a>
				<h3><i class="icon-hand-right"></i>Nueva Marca </h3>
			</div>
			<div class="modal-body">
				
			<ul>
				<li>
					<label for="id_descripcion">Marca</label><input type="text" id="id_descripcion" name="descripcion"></li>
			</ul>
			</div>
			<div class="modal-footer">
				<button class="btn btn-success btn-large "id="btn-add-marca" type="button">Registrar</button>
				<button class="btn" data-dismiss="modal">Cancelar</button>
			</div>
		</form>
	</section>
	
	<section id="smodelo" style="display:none;" class="modal fade hide ">
		<form id="frm-modelo" method="POST">{% csrf_token %}
			<div class="modal-hade">
				<a href="" class="close" data-dismiss="modal">x</a>
				<h3><i class="icon-hand-right"></i> Nuevo Modelo</h3>
			</div>
			<div class="modal-body">	
			<ul>
				 <li>
                	<label for="id_descripcion">Modelo</label>
                	<input type="text" id="id_descripcion" name="descripcion">
                </li>
			</ul>
			</div>
			<div class="modal-footer">
				<button type="button"class="btn btn-success btn-large" id="btn-add-modelo">Registrar</button>
				<button class="btn" data-dismiss="modal">
					Cancelar</button>
			</div>
		</form>
	</section>
	<section id="sclase" style="display:none;" class="modal hide fade">
		<form id="frm-clase" method="POST">{% csrf_token %}
			<div class="modal-hade">
				<a href="" class="close" data-dismiss="model">x</a>
				<h3><i class="icon-hand-right"></i>Nueva Clase</h3>
			</div>
			<div class="modal-body">
				
			<ul>
             <li>
             	<label for="id_descripcion">Clase</label><input type="text" id="id_descripcion" name="descripcion">
             </li>
          	</ul>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-success btn-large" id="btn-add-clase" >Registrar</button>
				<button class="btn"data-dismiss="modal" >Cancelar</button>
			</div>
		</form>
	</section>
	<section id="scategoria" style="display:none;" class="modal hide fade">
		<form method="POST" id="frm-categoria">{% csrf_token %}
			<div class="modal-hade">
				<a href="" class="close" data-dismiss="modal">x</a>
				<h3><i class="icon-hand-right"></i>Nueva Categoria</h3>
			</div>
			<div class="modal-body">
				
			<ul>
				<li>
					<label for="id_categoria">Categoria</label>
					<input type="text" id="id_categoria" name="categoria">
				</li>
			</ul>
			</div>
			<div class="modal-footer">
				<button type="button" id="btn-add-categoria"class="btn btn-success btn-large">Registrar</button>
				<button class="btn" data-dismiss="modal">Cancelar</button>
			</div>
		</form>
	</section>

{% endblock %}
{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js"></script>
	<script src="/static/js/vehiculos/add.js"></script>
	<script src="/static/js/jquery.combobox.js"></script>
	<script src="https://raw.github.com/carhartl/jquery-cookie/master/jquery.cookie.js"></script>
{% endblock %}

scm/templates/vehiculos/list_licencia.html
{% extends 'base.html' %}
{% block title %}
        busqueda de papeletas
{% endblock%}
{% block menu %}
    <ul>
           <li> <a href="/vehiculos/add/licencia/">add Licenciea </a></li>
           <li><a href="/pagos/">pagos</a></li>

    </ul>
{% endblock %}

{% block content%}
        <h2> Busqueda de papeletas por nro de placa </h2>
        <table>
		<thead>
		 	<tr>
		 		<th>Nombre</th>
				<th>Nro Licencia</th>
				<th>Clase</th>
				<th>Categoria</th>
				<th>Fecha Emision</th>
				<th>Fecha Vencimiento</th>
				<th> &nbsp;</th>

			</tr>
		</thead>
		
		
				{% for licencia in list_licencia %}
		<tr>
			<td>{{ licencia.propconduc_id }} </td>
		  	<td>{{ licencia.nro_licencia }}</td>
			<td>{{ licencia.clase }}</td>
			<td>{{ licencia.categoria }}</td>
			<td>{{ licencia.fecha_emision }}</td>
			<td>{{ licencia.fecha_vencimiento }}</td>
			<td><a href="/vehiculos/update/licencia/{{ licencia.id}}"> Editar </a></td>
		</tr>
			{% endfor %}
	<table>

{% endblock %}

scm/templates/vehiculos/list_soat.html
{% extends 'base.html' %}
{% block title %}
        busqueda de papeletas
{% endblock%}
{% block menu %}
    <ul>
           <li> <a href="/vehiculos/add/soat/">add Soat </a></li>
           <li><a href="/pagos/">pagos</a></li>

    </ul>
{% endblock %}

{% block content%}
      <table>
      <tr>
        <th>Placa</th>
        <th>Fecha Emision</th>
        <th>Fecha Caducidad</th>
        <th>Codigo del Soat</th>
        <th>Condicion</th>
       </tr>
    
         {% for vehiculo in meses %}
          
          
            
            {% for vehiculo in vehiculo.soat %}
           <tr> 
             
            <tr><td> {{ vehiculo.vehiculo_id }}</td>
            <td> {{ vehiculo.fecha_caducidad }}</td>
            <td>{{ vehiculo.codigo_soat }}</td>
            <td> caducado </td>
            <td>
            <a href="/vehiculos/update/soat/{{ vehiculo.vehiculo_id }}">Editar</a>
           </td>
         </tr>
         
         {% endfor %}
              
          {% endfor %}
      

   </table>


{% endblock %}